http:
  routers:
    api-router:
      rule: "Host(`localhost`)"
      service: api-service
      entryPoints:
        - web

  services:
    api-service:
      loadBalancer:
        servers:
          - url: "https://api.cmet.pt"