# http routing section
http:
  routers:
    # Define a connection between requests and services
    to-whoami:
      rule: "Host(`api.example.com`) && PathPrefix(`/whoami/`)"
      # If the rule matches, forward to the whoami service (declared below)
      service: api

  services:
    api:
      loadBalancer:
        servers:
        - url: https://api.cmet.pt